# Build the SN360 EDR minifilter driver (Phase E6.1 / E6.2).
#
# Production build script — requires the Windows Driver Kit (WDK)
# installed at `C:\Program Files (x86)\Windows Kits\10\` and a
# Microsoft-issued kernel-mode code-signing certificate.
#
# This is NOT exercised in CI. Refer to
# `docs/edr-parity/PRODUCTISATION-WINDOWS.md` for the full WHQL
# pipeline including the WHCP submission step that runs on Microsoft
# infrastructure.

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [ValidateSet('Debug', 'Release')]
    [string]$Configuration = 'Release',

    [Parameter(Mandatory = $false)]
    [ValidateSet('x64', 'arm64')]
    [string]$Platform = 'x64',

    [Parameter(Mandatory = $false)]
    [string]$DriverProject = "$PSScriptRoot\sda-edr-minifilter\sda-edr-minifilter.vcxproj",

    [Parameter(Mandatory = $false)]
    [string]$OutputDir = "$PSScriptRoot\..\..\target\windows-driver"
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

function Find-MSBuild {
    # The WDK ships with msbuild via Visual Studio Build Tools.
    # We resolve the path via `vswhere` rather than hard-coding it
    # so the script works on both stock VS Enterprise installs and
    # the standalone Build Tools SKU used on the WHQL signing box.
    $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
    if (-not (Test-Path $vswhere)) {
        throw "vswhere.exe not found at $vswhere; install Visual Studio Build Tools first."
    }
    $vsRoot = & $vswhere -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
    if (-not $vsRoot) {
        throw "No Visual Studio installation with MSBuild detected."
    }
    return Join-Path $vsRoot 'MSBuild\Current\Bin\MSBuild.exe'
}

function Test-WDKInstalled {
    $wdkRoot = 'C:\Program Files (x86)\Windows Kits\10\Include'
    if (-not (Test-Path $wdkRoot)) {
        throw "Windows Driver Kit not found at $wdkRoot. Install the WDK before running this script."
    }
}

function Invoke-Build {
    param(
        [string]$MSBuildPath,
        [string]$Project,
        [string]$Configuration,
        [string]$Platform,
        [string]$OutputDir
    )

    if (-not (Test-Path $OutputDir)) {
        New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null
    }

    & $MSBuildPath $Project `
        "/p:Configuration=$Configuration" `
        "/p:Platform=$Platform" `
        "/p:OutDir=$OutputDir\" `
        "/t:Build" `
        "/v:minimal"

    if ($LASTEXITCODE -ne 0) {
        throw "msbuild failed with exit code $LASTEXITCODE."
    }
}

Test-WDKInstalled
$msbuild = Find-MSBuild
Write-Host "Using MSBuild: $msbuild"
Write-Host "Building $DriverProject ($Configuration / $Platform) → $OutputDir"

if (-not (Test-Path $DriverProject)) {
    Write-Warning "Driver project file $DriverProject not found."
    Write-Warning "Phase E6.1 ships only the WDK skeleton; the .vcxproj is generated by the WDK template wizard."
    Write-Warning "See docs/edr-parity/PRODUCTISATION-WINDOWS.md § 'Driver scaffolding' for the wizard invocation."
    exit 2
}

Invoke-Build -MSBuildPath $msbuild -Project $DriverProject -Configuration $Configuration -Platform $Platform -OutputDir $OutputDir

Write-Host "Driver build complete. Next: run .\sign-driver.ps1 to submit to WHCP."
