//! Remote-support session capture & transport.
//!
//! This module is the cross-platform PAL surface for the
//! Device Control remote-support feature.  The
//! [`RemoteSupportProvider`] trait is the binding spec from
//! `docs/architecture.md` § 4.1 (Trait surface); per-OS implementations
//! ship in this crate behind `cfg`-gates.
//!
//! Current scope (this file): every per-OS implementation is a
//! deliberate **stub** that returns
//! [`RemoteSupportError::NotSupported`] from
//! [`RemoteSupportProvider::start_session`]. The real capture +
//! transport stacks land in later phases:
//!
//! * **Linux** — PipeWire / XCB capture (Wayland + X11), gated on
//!   explicit user consent — see `docs/device-control.md` § 9.
//! * **macOS** — ScreenCaptureKit-style API.
//! * **Windows** — Windows Graphics Capture (WGC) + DDA-style
//!   transport.
//!
//! Higher-level orchestration (consent flow, time-bounded sessions,
//! evidence emission) lives in `crates/sda-remote-support`. That
//! crate calls into this trait via `Box<dyn RemoteSupportProvider>`
//! so the supervisor can swap a real provider for the stub in
//! tests without touching production code.

use chrono::{DateTime, Duration, Utc};
use serde::{Deserialize, Serialize};
use std::io;

/// Errors produced by [`RemoteSupportProvider`] implementations.
#[derive(Debug, thiserror::Error)]
pub enum RemoteSupportError {
    /// The underlying capture API or transport returned an error.
    #[error("remote-support backend failed: {0}")]
    Backend(String),
    /// The host platform has no capture backend yet.
    #[error("remote-support not supported on this platform")]
    NotSupported,
    /// The user declined the consent prompt.
    #[error("remote-support consent denied")]
    ConsentDenied,
    /// Caller-supplied input failed validation.
    #[error("remote-support input invalid: {0}")]
    InvalidInput(String),
    /// I/O error while talking to the OS capture / transport stack.
    #[error("remote-support IO error: {0}")]
    Io(#[from] io::Error),
}

/// Inputs to [`RemoteSupportProvider::start_session`].
///
/// `operator_id` identifies the human or service-account requesting
/// the session — it surfaces in the consent UI so the end-user can
/// see exactly who is asking. `max_duration` is a hard wall-clock
/// cap enforced by `sda-remote-support`; the PAL layer is allowed
/// to truncate sessions earlier if the underlying capture API has
/// its own limit. `consent_required` MUST be `true` for any
/// production session; the field exists so unit tests can build
/// `SessionParams` without a consent fixture.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionParams {
    /// Opaque, server-issued identifier for the operator requesting
    /// the session (e.g. helpdesk agent username, automation tag).
    pub operator_id: String,
    /// Hard wall-clock cap on the session length. The supervisor
    /// also enforces this; the PAL layer simply gets it for log
    /// context.
    pub max_duration: Duration,
    /// Whether the agent must show a consent banner and block until
    /// the user accepts. Always `true` outside unit tests per
    /// `docs/device-control.md` § 9.
    pub consent_required: bool,
}

/// Opaque handle to a started remote-support session.
///
/// `session_id` is generated by the agent (UUIDv4) so the control
/// plane and the local audit chain can correlate the session
/// without trusting an operator-supplied identifier.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SessionHandle {
    /// Agent-issued, opaque session ID.
    pub session_id: String,
    /// Wall-clock UTC start time of the session.
    pub started_at: DateTime<Utc>,
}

/// Cross-platform remote-support capture & transport surface.
///
/// Implementations MUST be `Send + Sync` because the supervisor
/// holds a `Box<dyn RemoteSupportProvider>` across `await` points
/// in the Tokio runtime.  Per-OS stubs are zero-sized and trivially
/// satisfy these bounds.
pub trait RemoteSupportProvider: Send + Sync {
    /// Begin a remote-support session subject to `params`.
    ///
    /// Per-OS stubs return [`RemoteSupportError::NotSupported`].
    fn start_session(&self, params: &SessionParams) -> Result<SessionHandle, RemoteSupportError>;

    /// Tear down a running session. Idempotent — calling
    /// `end_session` on an already-terminated handle MUST NOT
    /// return an error.
    fn end_session(&self, handle: &SessionHandle) -> Result<(), RemoteSupportError>;
}

// =====================================================================
// Per-OS stub providers
// =====================================================================

/// Linux stub provider.  Will host the PipeWire / XCB
/// capture backend in a later phase; today every call returns
/// [`RemoteSupportError::NotSupported`].
#[cfg(target_os = "linux")]
pub mod linux_impl {
    use super::*;

    /// Linux stub for [`RemoteSupportProvider`].
    #[derive(Debug, Default)]
    pub struct LinuxRemoteSupportProvider;

    impl LinuxRemoteSupportProvider {
        /// Construct a fresh stub provider.
        pub fn new() -> Self {
            Self
        }
    }

    impl RemoteSupportProvider for LinuxRemoteSupportProvider {
        fn start_session(
            &self,
            _params: &SessionParams,
        ) -> Result<SessionHandle, RemoteSupportError> {
            Err(RemoteSupportError::NotSupported)
        }

        fn end_session(&self, _handle: &SessionHandle) -> Result<(), RemoteSupportError> {
            // Idempotent — even on the stub end_session must succeed
            // so the supervisor's cleanup paths stay simple.
            Ok(())
        }
    }
}

#[cfg(target_os = "linux")]
pub use linux_impl::LinuxRemoteSupportProvider;

/// macOS stub provider.  Will host the ScreenCaptureKit-style
/// backend in a later phase; today every call returns
/// [`RemoteSupportError::NotSupported`].
#[cfg(target_os = "macos")]
pub mod mac_impl {
    use super::*;

    /// macOS stub for [`RemoteSupportProvider`].
    #[derive(Debug, Default)]
    pub struct MacRemoteSupportProvider;

    impl MacRemoteSupportProvider {
        /// Construct a fresh stub provider.
        pub fn new() -> Self {
            Self
        }
    }

    impl RemoteSupportProvider for MacRemoteSupportProvider {
        fn start_session(
            &self,
            _params: &SessionParams,
        ) -> Result<SessionHandle, RemoteSupportError> {
            Err(RemoteSupportError::NotSupported)
        }

        fn end_session(&self, _handle: &SessionHandle) -> Result<(), RemoteSupportError> {
            Ok(())
        }
    }
}

#[cfg(target_os = "macos")]
pub use mac_impl::MacRemoteSupportProvider;

/// Windows stub provider.  Will host the WGC + DDA backend in
/// a later phase; today every call returns
/// [`RemoteSupportError::NotSupported`].
#[cfg(target_os = "windows")]
pub mod windows_impl {
    use super::*;

    /// Windows stub for [`RemoteSupportProvider`].
    #[derive(Debug, Default)]
    pub struct WindowsRemoteSupportProvider;

    impl WindowsRemoteSupportProvider {
        /// Construct a fresh stub provider.
        pub fn new() -> Self {
            Self
        }
    }

    impl RemoteSupportProvider for WindowsRemoteSupportProvider {
        fn start_session(
            &self,
            _params: &SessionParams,
        ) -> Result<SessionHandle, RemoteSupportError> {
            Err(RemoteSupportError::NotSupported)
        }

        fn end_session(&self, _handle: &SessionHandle) -> Result<(), RemoteSupportError> {
            Ok(())
        }
    }
}

#[cfg(target_os = "windows")]
pub use windows_impl::WindowsRemoteSupportProvider;

// =====================================================================
// Default factory
// =====================================================================

/// Returns the platform-default [`RemoteSupportProvider`] for this
/// host.
///
/// On unsupported targets returns `None` so the agent can run with
/// remote-support disabled rather than panicking at startup.
pub fn default_remote_support_provider() -> Option<Box<dyn RemoteSupportProvider>> {
    #[cfg(target_os = "linux")]
    {
        Some(Box::new(LinuxRemoteSupportProvider::new()))
    }
    #[cfg(target_os = "macos")]
    {
        Some(Box::new(MacRemoteSupportProvider::new()))
    }
    #[cfg(target_os = "windows")]
    {
        Some(Box::new(WindowsRemoteSupportProvider::new()))
    }
    #[cfg(not(any(target_os = "linux", target_os = "macos", target_os = "windows")))]
    {
        None
    }
}

// =====================================================================
// Tests
// =====================================================================

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_params() -> SessionParams {
        SessionParams {
            operator_id: "ops@example.com".into(),
            max_duration: Duration::minutes(30),
            consent_required: true,
        }
    }

    fn sample_handle() -> SessionHandle {
        SessionHandle {
            session_id: "sess-deadbeef".into(),
            started_at: Utc::now(),
        }
    }

    #[test]
    fn session_params_round_trips_through_json() {
        let p = sample_params();
        let json = serde_json::to_string(&p).expect("encode");
        let back: SessionParams = serde_json::from_str(&json).expect("decode");
        assert_eq!(p, back);
    }

    #[test]
    fn session_handle_round_trips_through_json() {
        let h = sample_handle();
        let json = serde_json::to_string(&h).expect("encode");
        let back: SessionHandle = serde_json::from_str(&json).expect("decode");
        assert_eq!(h, back);
    }

    #[test]
    fn default_provider_is_present_on_supported_targets() {
        // The factory MUST return Some on every target the workspace
        // supports — Linux/macOS/Windows. If a future port lands on a
        // target with no backend, this assertion will fail and remind
        // us to extend the factory or return None deliberately.
        #[cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))]
        {
            let p = default_remote_support_provider();
            assert!(p.is_some(), "expected platform stub provider");
        }
    }

    #[test]
    fn stub_start_session_returns_not_supported() {
        // The per-OS stubs deliberately fail closed. End-to-end
        // tests in `sda-remote-support` rely on this so the
        // supervisor exposes the NotSupported state on the bus.
        let provider = default_remote_support_provider();
        if let Some(provider) = provider {
            let err = provider.start_session(&sample_params()).err();
            assert!(matches!(err, Some(RemoteSupportError::NotSupported)));
        }
    }

    #[test]
    fn stub_end_session_is_idempotent() {
        // end_session must succeed on an unknown handle so the
        // supervisor's revoke / shutdown paths can be unconditional.
        let provider = default_remote_support_provider();
        if let Some(provider) = provider {
            let h = sample_handle();
            assert!(provider.end_session(&h).is_ok());
            assert!(
                provider.end_session(&h).is_ok(),
                "second call must also succeed"
            );
        }
    }

    #[test]
    fn trait_object_compiles_for_send_sync_and_box() {
        // Compile-time check: the trait must be object-safe AND
        // `Send + Sync` so the supervisor can hold it across
        // `await` points.
        fn _assert_object_safe(_: Box<dyn RemoteSupportProvider>) {}
        fn _assert_send_sync<T: Send + Sync>() {}
        _assert_send_sync::<Box<dyn RemoteSupportProvider>>();
    }
}
